/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypanels;

import singaleton.MyLib;
import java.sql.*;
import javax.swing.JOptionPane;
public class ItemReg extends javax.swing.JPanel {

    /**
     * Creates new form ItemReg
     */
    public ItemReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        T3 = new javax.swing.JTextArea();
        Addbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Item Registration");
        add(jLabel1);
        jLabel1.setBounds(150, 40, 310, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Item Name");
        add(jLabel2);
        jLabel2.setBounds(100, 120, 100, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Type");
        add(jLabel3);
        jLabel3.setBounds(100, 180, 70, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Description");
        add(jLabel4);
        jLabel4.setBounds(90, 300, 100, 22);

        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        add(T1);
        T1.setBounds(200, 120, 320, 30);

        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });
        add(T2);
        T2.setBounds(200, 180, 320, 30);

        T3.setColumns(20);
        T3.setRows(5);
        jScrollPane1.setViewportView(T3);

        add(jScrollPane1);
        jScrollPane1.setBounds(200, 300, 320, 100);

        Addbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Addbtn.setForeground(new java.awt.Color(0, 153, 0));
        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        add(Addbtn);
        Addbtn.setBounds(260, 450, 90, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Quantity");
        add(jLabel5);
        jLabel5.setBounds(100, 250, 70, 22);

        T4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(T4);
        T4.setBounds(200, 240, 320, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
        String item_name,type,desc;
        item_name=T1.getText();
        type=T2.getText();
        desc=T3.getText();
        String qty=T4.getText();
        String msg="";
        if(item_name==null || item_name.equals(""))
        {
            msg="Enter Item Name";
            T1.requestFocus();
        }
        else if(type==null || type.equals(""))
        {
            msg="Enter Type";
            T2.requestFocus();
        }
        else if(type==null || type.equals(""))
        {
            msg="Enter description";
            T3.requestFocus();
        }
         else if(qty==null || qty.equals(""))
        {
            msg="Enter Quantity";
            T4.requestFocus();
        }
        else
        {
            try
            {
                Connection cn=new MyLib().getConnection();
                String sql="insert into itemdata values(?,?,?,?)";
                PreparedStatement p1=cn.prepareStatement(sql);
                p1.setString(1, item_name);
                p1.setString(2,type);
                p1.setString(3, qty);
                p1.setString(4, desc);
                int a=p1.executeUpdate();
                if(a==1)
                {
                    msg="Item Saved ";
                    T1.setText("");
                    T2.setText("");
                    T3.setText("");
                    T1.requestFocus();
                }
                else
                {
                    msg="Item not saved";
                }

            }
            catch(Exception e)
            {
                msg=""+e;
            }
        }
        JOptionPane.showMessageDialog(null, msg);
    }//GEN-LAST:event_AddbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextArea T3;
    private javax.swing.JTextField T4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
