/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypanels;

import singaleton.MyLib;
import java.sql.*;
import javax.swing.JOptionPane;
public class OperatorReg extends javax.swing.JPanel {

    /**
     * Creates new form OperatorReg
     */
    public OperatorReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T7 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        T1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        T4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Confirm Password");
        add(jLabel1);
        jLabel1.setBounds(130, 440, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Contact");
        add(jLabel2);
        jLabel2.setBounds(210, 210, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Joining Date");
        add(jLabel3);
        jLabel3.setBounds(170, 300, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Email");
        add(jLabel4);
        jLabel4.setBounds(220, 350, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Password");
        add(jLabel5);
        jLabel5.setBounds(190, 390, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Name");
        add(jLabel6);
        jLabel6.setBounds(220, 130, 50, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Designation");
        add(jLabel7);
        jLabel7.setBounds(180, 170, 100, 30);
        add(T2);
        T2.setBounds(310, 160, 160, 30);
        add(T3);
        T3.setBounds(310, 210, 160, 30);
        add(T5);
        T5.setBounds(310, 300, 160, 30);
        add(T6);
        T6.setBounds(310, 350, 160, 30);
        add(T7);
        T7.setBounds(310, 390, 160, 30);
        add(T8);
        T8.setBounds(310, 440, 160, 30);
        add(T1);
        T1.setBounds(310, 120, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(250, 490, 130, 31);
        add(T4);
        T4.setBounds(310, 250, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Address");
        add(jLabel8);
        jLabel8.setBounds(210, 250, 70, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 255));
        jLabel9.setText("Operator Registration");
        add(jLabel9);
        jLabel9.setBounds(170, 40, 350, 28);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name,designation,contact,joining_date,email,pass,confirm;
        name=T1.getText();
        designation=T2.getText();
        contact=T3.getText();
        String address =T4.getText();
        joining_date=T5.getText();
        email=T6.getText();
        pass=T7.getText();
        confirm=T8.getText();
        String msg="";
        if(name==null || name.trim().equals(""))
        {
            msg="Enter Name";
            T1.requestFocus();
        }
        else if(designation==null || designation.trim().equals(""))
        {
            msg="Enter Desiganitation";
            T2.requestFocus();
        }
        else if(contact==null || contact.trim().equals(""))
        {
            msg="Enter Contact";
            T3.requestFocus();
        }
        else if(address==null || address.trim().equals(""))
        {
            msg="Enter Address";
            T4.requestFocus();
        }
        else if(joining_date==null || joining_date.trim().equals(""))
        {
            msg="Enter Joining_date";
            T5.requestFocus();
        }
        else if(email==null || email.trim().equals(""))
        {
            msg="Enter Email";
            T6.requestFocus();
        }
        else if(pass==null || pass.trim().equals(""))
        {
            msg="Enter Password";
            T7.requestFocus();
        }
        else if(confirm==null || confirm.trim().equals(""))
        {
            msg="Enter Confirm Password";
            T8.requestFocus();
        }
        else if(pass.equals(confirm)==false)
        {
            msg="Password Not Match";
            T7.setText("");
            T8.setText("");
            T7.requestFocus();
        }
        else
        {
            try
            {
                Connection cn=new MyLib().getConnection();
                String sql="insert into oprtdata values(?,?,?,?,?,?)";
                String sql1="insert into logindata values(?,?,?)";
                PreparedStatement p1=cn.prepareStatement(sql);
                PreparedStatement p2=cn.prepareStatement(sql1);

                p1.setString(1, name);
                p1.setString(2, designation);
                p1.setString(3, contact);
                p1.setString(4, address);
                p1.setString(5, joining_date);
                p1.setString(6, email);

                p2.setString(1, email);
                p2.setString(2, pass);
                p2.setString(3, "Operator");

                int a=p1.executeUpdate();
                int b=p2.executeUpdate();

                if(a==1 && b==1)
                {
                    msg="Data Saves And Login Is Created";
                    T1.setText("");
                    T2.setText("");
                    T3.setText("");
                    T4.setText("");
                    T5.setText("");
                    T6.setText("");
                    T7.setText("");
                    T8.setText("");
                    T1.requestFocus();

                }
                else if(a==1)
                {
                    msg="Only Data is saved";
                }
                else if(b==1)
                {
                    msg="Only Login is Created";
                }
                else
                {
                    msg="No Data is saved & No login is created";
                }

            }
            catch(Exception e)
            {
                msg=""+e;
            }
        }
        JOptionPane.showMessageDialog(null, msg);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
