/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypanels;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import singaleton.MyLib;

/**
 *
 * @author V
 */
public class Search extends javax.swing.JPanel {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        SearchByName = new javax.swing.JButton();
        SearchByType = new javax.swing.JButton();

        setLayout(null);
        add(T1);
        T1.setBounds(170, 50, 320, 30);

        tbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Type", "Quantity", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 190, 540, 220);

        SearchByName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SearchByName.setForeground(new java.awt.Color(0, 153, 0));
        SearchByName.setText("SearchByName");
        SearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByNameActionPerformed(evt);
            }
        });
        add(SearchByName);
        SearchByName.setBounds(120, 130, 150, 31);

        SearchByType.setBackground(new java.awt.Color(204, 204, 204));
        SearchByType.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SearchByType.setForeground(new java.awt.Color(0, 153, 51));
        SearchByType.setText("SearchByType");
        SearchByType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchByTypeActionPerformed(evt);
            }
        });
        add(SearchByType);
        SearchByType.setBounds(350, 130, 150, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByNameActionPerformed
        // TODO add your handling code here:
        String msg="";
        DefaultTableModel tblmodel=(DefaultTableModel) tbl.getModel();

        try
        {
            String pattern=T1.getText();
            Connection cn=new MyLib().getConnection();
            String sql="select * from itemdata where item_name like '%"+pattern.trim()+"%'";

            PreparedStatement p1=cn.prepareStatement(sql);
            ResultSet r1=p1.executeQuery();

            for(int i=0;i<tblmodel.getRowCount();)
            tblmodel.removeRow(i);
            if(tblmodel.getRowCount()==1)
            tblmodel.removeRow(0);

            while(r1.next())
            {
                String item_name=r1.getString("item_name");
                String type=r1.getString("type");
                String desc=r1.getString("description");
                String qty=r1.getString("qty");

                String tbdata[]={item_name,type,qty,desc};
                //   DefaultTableModel tblmodel=(DefaultTableModel) tbl.getModel();

                tblmodel.addRow(tbdata);

            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_SearchByNameActionPerformed

    private void SearchByTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchByTypeActionPerformed
        // TODO add your handling code here:
        String msg="";
        DefaultTableModel tblmodel=(DefaultTableModel) tbl.getModel();

        try
        {
            String pattern=T1.getText();
            Connection cn=new MyLib().getConnection();
            String sql="select * from itemdata where type like '%"+pattern.trim()+"%'";

            PreparedStatement p1=cn.prepareStatement(sql);
            ResultSet r1=p1.executeQuery();

            for(int i=0;i<tblmodel.getRowCount();)
            tblmodel.removeRow(i);
            if(tblmodel.getRowCount()==1)
            tblmodel.removeRow(0);

            while(r1.next())
            {
                String item_name=r1.getString("item_name");
                String type=r1.getString("type");
                String desc=r1.getString("description");
                String qty=r1.getString("qty");

                String tbdata[]={item_name,type,qty,desc};
                //   DefaultTableModel tblmodel=(DefaultTableModel) tbl.getModel();

                tblmodel.addRow(tbdata);

            }
        }
        catch(Exception e)
        {

        }

    }//GEN-LAST:event_SearchByTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchByName;
    private javax.swing.JButton SearchByType;
    private javax.swing.JTextField T1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
