/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypanels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import singaleton.MyLib;

/**
 *
 * @author V
 */
public class StockIn extends javax.swing.JPanel {

    /**
     * Creates new form StockIn
     */
    public StockIn() {
        initComponents();
        try
        {
            Connection cn=new MyLib().getConnection();
            String sql="select item_name from itemdata";
            PreparedStatement p1=cn.prepareStatement(sql);
            ResultSet r1=p1.executeQuery();
            DefaultComboBoxModel model=new DefaultComboBoxModel();
            
            while(r1.next())
            {
                String item=r1.getString("item_name");
                model.addElement(item);
            }
            B1.setModel(model);
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Fatch item name"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B1 = new javax.swing.JComboBox();
        ShowBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Item");
        add(jLabel1);
        jLabel1.setBounds(210, 100, 33, 22);

        B1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        B1.setForeground(new java.awt.Color(51, 51, 255));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        add(B1);
        B1.setBounds(280, 100, 200, 30);

        ShowBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ShowBtn.setForeground(new java.awt.Color(0, 153, 0));
        ShowBtn.setText("Show");
        ShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBtnActionPerformed(evt);
            }
        });
        add(ShowBtn);
        ShowBtn.setBounds(530, 100, 90, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Name");
        add(jLabel2);
        jLabel2.setBounds(200, 160, 43, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Qty");
        add(jLabel3);
        jLabel3.setBounds(197, 280, 30, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Type");
        add(jLabel4);
        jLabel4.setBounds(200, 220, 38, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Deposot Qty");
        add(jLabel5);
        jLabel5.setBounds(160, 350, 100, 22);

        T1.setEditable(false);
        T1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(T1);
        T1.setBounds(270, 160, 240, 28);

        T2.setEditable(false);
        T2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(T2);
        T2.setBounds(270, 280, 240, 28);

        T3.setEditable(false);
        T3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(T3);
        T3.setBounds(270, 220, 240, 28);

        T4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(T4);
        T4.setBounds(270, 350, 240, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Stock-In");
        add(jLabel6);
        jLabel6.setBounds(310, 40, 140, 30);

        AddBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(0, 153, 0));
        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        add(AddBtn);
        AddBtn.setBounds(190, 530, 100, 40);

        CancelBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(255, 0, 0));
        CancelBtn.setText("Cancel");
        add(CancelBtn);
        CancelBtn.setBounds(410, 530, 100, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("From or To");
        add(jLabel7);
        jLabel7.setBounds(170, 420, 90, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Remark");
        add(jLabel8);
        jLabel8.setBounds(200, 470, 60, 22);

        T5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(T5);
        T5.setBounds(270, 410, 240, 30);

        T6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(T6);
        T6.setBounds(270, 460, 240, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        String Item;

    }//GEN-LAST:event_B1ActionPerformed

    private void ShowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBtnActionPerformed
        // TODO add your handling code here:
        String msg="";
        try
        {
            String item=B1.getSelectedItem().toString();
            Connection cn= new MyLib().getConnection();
            String sql="select * from itemdata where item_name=?";
            PreparedStatement p1=cn.prepareStatement(sql);
            p1.setString(1, item);
            ResultSet r1=p1.executeQuery();
            if(r1.next())
            {
                String a,b,c;
                a=r1.getString("item_name");
                b=r1.getString("type");
                c=r1.getString("qty");

                T1.setText(a);
                T2.setText(c);
                T3.setText(b);
            }
        }
        catch(Exception e)
        {
            msg=""+e;
        }

    }//GEN-LAST:event_ShowBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        String msg="";
        String item_name,from_or_to,remarks,desc,qty;
        qty=T4.getText();
        from_or_to=T5.getText();
        remarks=T6.getText();
        item_name=T1.getText();
        // String t_type=T7.getText();

        if(qty==null || qty.trim().equals(""))
        {
            msg="Enter New Quantity";
            T4.requestFocus();
        }
        else if(from_or_to==null || from_or_to.trim().equals(""))
        {

            msg="Enter New from or to";
            T5.requestFocus();
        }
        else if(remarks==null || remarks.trim().equals(""))
        {

            msg="Enter Remarks";
            T6.requestFocus();
        }
        //         else if(t_type==null || t_type.trim().equals(""))
        //        {
            //
            //            msg="Enter Remarks";
            //            T7.requestFocus();
            //        }

        else
        {
            try
            {
                Connection cn=new MyLib().getConnection();
                String s1="update itemdata set qty=qty+? where item_name=?";
                String s2="insert into stock_transtation  values(0,?,?,?,?,?,?)";

                PreparedStatement p1=cn.prepareStatement(s1);
                PreparedStatement p2=cn.prepareStatement(s2);
                p1.setString(1, qty);
                p1.setString(2, item_name);

                p2.setString(1,item_name);
                p2.setString(2,qty);
                p2.setLong(3,System.currentTimeMillis());
                p2.setString(4,"Deposit");
                p2.setString(5,from_or_to);
                p2.setString(6,remarks);

                int a=p1.executeUpdate();
                int b=p2.executeUpdate();

                if(a==1 && b==1)
                {
                    msg="item data & stock_transtion succesfully saved";
                    T1.setText("");
                    T2.setText("");
                    T3.setText("");
                    T4.setText("");
                    T5.setText("");
                    T6.setText("");

                    T4.requestFocus();
                }
                else if(a==1)
                {
                    msg="only item data saved";
                    T1.setText("");
                    T2.setText("");
                    T3.setText("");

                }
                else if(b==1)
                {
                    msg="only stock Transitation saved";
                    T4.setText("");
                    T5.setText("");
                    T6.setText("");

                    T4.requestFocus();
                }
                else
                {
                    msg="No data saved in both";
                }

            }
            catch(Exception e)
            {
                msg=""+e;
            }

        }
        javax.swing.JOptionPane.showMessageDialog(null, msg);

    }//GEN-LAST:event_AddBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JComboBox B1;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton ShowBtn;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
